using System;

namespace StateLandGovernance.GovernanceIntelligence.Domain.Events;

/// <summary>
/// Foundational base class for all domain events generated by the GovernanceIntelligence module.
/// </summary>
public abstract record GovernanceEvent
{
    public Guid Id { get; } = Guid.NewGuid();
    public DateTime OccurredOn { get; } = DateTime.UtcNow;
}
