// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence;

#nullable disable

namespace StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GovernanceIntelligenceDbContext))]
    [Migration("20261008074415_GovernanceIntelligence_AddEarlyGovernanceCommissionerReferrals")]
    partial class GovernanceIntelligence_AddEarlyGovernanceCommissionerReferrals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("governance_intelligence")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplaintClassificationAssessmentEntity", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<decimal>("AdministrativeProceduralIntegrityProbability")
                        .HasPrecision(18, 17)
                        .HasColumnType("numeric(18,17)")
                        .HasColumnName("administrative_procedural_integrity_probability");

                    b.Property<string>("AdvisoryNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("advisory_note");

                    b.Property<DateTimeOffset>("AssessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at_utc");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("case_id");

                    b.Property<string>("ClosedSetNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("closed_set_note");

                    b.Property<string>("ComplaintText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("complaint_text");

                    b.Property<decimal>("LeaseRevenuePaymentEnforcementProbability")
                        .HasPrecision(18, 17)
                        .HasColumnType("numeric(18,17)")
                        .HasColumnName("lease_revenue_payment_enforcement_probability");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("PredictedCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("predicted_category");

                    b.Property<decimal>("ProtectedEnvironmentalLeaseMisuseProbability")
                        .HasPrecision(18, 17)
                        .HasColumnType("numeric(18,17)")
                        .HasColumnName("protected_environmental_lease_misuse_probability");

                    b.Property<decimal>("UnauthorizedAllocationTransferUseProbability")
                        .HasPrecision(18, 17)
                        .HasColumnType("numeric(18,17)")
                        .HasColumnName("unauthorized_allocation_transfer_use_probability");

                    b.HasKey("AssessmentId");

                    b.ToTable("complaint_classification_assessments", "governance_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_complaint_classification_assessments_probability_range", "administrative_procedural_integrity_probability >= 0 AND administrative_procedural_integrity_probability <= 1 AND lease_revenue_payment_enforcement_probability >= 0 AND lease_revenue_payment_enforcement_probability <= 1 AND unauthorized_allocation_transfer_use_probability >= 0 AND unauthorized_allocation_transfer_use_probability <= 1 AND protected_environmental_lease_misuse_probability >= 0 AND protected_environmental_lease_misuse_probability <= 1");

                            t.HasCheckConstraint("CK_complaint_classification_assessments_probability_sum", "abs(administrative_procedural_integrity_probability + lease_revenue_payment_enforcement_probability + unauthorized_allocation_transfer_use_probability + protected_environmental_lease_misuse_probability - 1.0) <= 0.000001");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeterministicEvaluationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FindingsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProposalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_compliance_eval_audit_id");

                    b.HasIndex("DeterministicEvaluationId")
                        .HasDatabaseName("idx_comp_eval_det_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_comp_eval_timestamp");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("idx_comp_eval_proposal_id");

                    b.ToTable("compliance_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("boolean");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceSection")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("RuleCode", "RuleVersion")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_rule_code_version");

                    b.ToTable("compliance_rules", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConditionalVerificationEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionalVerificationEvaluationId");

                    b.ToTable("condition_results", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpiredConditionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MandatoryConditionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingConditionsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PendingConditionsCount")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SatisfiedMandatoryCount")
                        .HasColumnType("integer");

                    b.Property<int>("SatisfiedOptionalCount")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SummaryExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalConditionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnsatisfiedMandatoryCount")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_cond_verif_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_cond_verif_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_cond_verif_subject_id");

                    b.ToTable("conditional_verification_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("DetectedConflictsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HighestSeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalEvaluatedDecisions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_conflict_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_conf_eval_timestamp");

                    b.ToTable("conflict_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictFindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConflictEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DetectionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvolvedDecisionIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvolvedInstitutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConflictEvaluationId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_conf_finding_subject_id");

                    b.ToTable("conflict_findings", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AbstentionCount")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("BlockingInstitutionCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConditionalApprovalCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConsensusEvaluationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ConsensusThresholdSatisfied")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MandatoryInstitutionsSatisfied")
                        .HasColumnType("boolean");

                    b.Property<int>("MissingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ParticipatingCount")
                        .HasColumnType("integer");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer");

                    b.Property<bool>("QuorumSatisfied")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SubmittedCount")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalExpectedInstitutions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_consensus_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_cons_eval_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_cons_eval_subject_id");

                    b.ToTable("consensus_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.EarlyGovernanceReferralEntity", b =>
                {
                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("case_id");

                    b.Property<string>("CommissionerReviewProcessReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("commissioner_review_process_reference");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<int>("DeliveryAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_attempt_count");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("delivery_state");

                    b.Property<string>("EvidenceReferencesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_references_json");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_failure_code");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("ReferralId");

                    b.HasIndex("AssessmentId")
                        .IsUnique();

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("DeliveryState");

                    b.HasIndex("CaseId", "RequestedAtUtc");

                    b.ToTable("early_governance_referrals", "governance_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_early_governance_referrals_delivery_attempt_count", "delivery_attempt_count >= 0");

                            t.HasCheckConstraint("CK_early_governance_referrals_delivery_state", "delivery_state IN ('Pending', 'Delivering', 'DeliveryFailed', 'Acknowledged')");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.EarlyGovernanceScreeningEvaluationEntity", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("InputVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("input_version");

                    b.Property<string>("ResultSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_snapshot_json");

                    b.Property<int>("SnapshotSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_schema_version");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("AssessmentId");

                    b.HasIndex("CaseId", "CreatedAtUtc");

                    b.ToTable("early_governance_screening_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EngineType")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionName")
                        .HasDatabaseName("idx_gov_audit_action_name");

                    b.HasIndex("EngineType")
                        .HasDatabaseName("idx_gov_audit_engine_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_gov_audit_timestamp");

                    b.ToTable("governance_audit_records", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExplanationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OverallSeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_gov_expl_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_gov_expl_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_gov_expl_subject_id");

                    b.ToTable("governance_explanations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GovernanceExplanationEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlainLanguageExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresHumanAttention")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceEngine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GovernanceExplanationEvaluationId");

                    b.ToTable("governance_explanation_items", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.InstitutionPositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConsensusEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SubmittedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsensusEvaluationId");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("idx_inst_pos_institution_id");

                    b.ToTable("institution_positions", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RegulatorySourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Checksum")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GazetteNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("regulatory_sources", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OverallRiskScore")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_risk_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_risk_eval_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_risk_eval_subject_id");

                    b.ToTable("risk_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskIndicatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndicatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InvolvedActorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RiskEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreContribution")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TriggeredRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RiskEvaluationId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_risk_ind_subject_id");

                    b.ToTable("risk_indicators", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RuleParameterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("idx_rule_param_rule_id");

                    b.ToTable("rule_parameters", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceRuleEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RegulatorySourceEntity", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Source");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionResultEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", "ConditionalVerificationEvaluation")
                        .WithMany("ConditionResults")
                        .HasForeignKey("ConditionalVerificationEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionalVerificationEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictFindingEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", "ConflictEvaluation")
                        .WithMany("Findings")
                        .HasForeignKey("ConflictEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConflictEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.EarlyGovernanceReferralEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.EarlyGovernanceScreeningEvaluationEntity", "Assessment")
                        .WithOne("Referral")
                        .HasForeignKey("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.EarlyGovernanceReferralEntity", "AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationItemEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", "ExplanationEvaluation")
                        .WithMany("Items")
                        .HasForeignKey("GovernanceExplanationEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExplanationEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.InstitutionPositionEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", "ConsensusEvaluation")
                        .WithMany("InstitutionPositions")
                        .HasForeignKey("ConsensusEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsensusEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskIndicatorEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", "RiskEvaluation")
                        .WithMany("RiskIndicators")
                        .HasForeignKey("RiskEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RuleParameterEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceRuleEntity", "Rule")
                        .WithMany("Parameters")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceRuleEntity", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", b =>
                {
                    b.Navigation("ConditionResults");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", b =>
                {
                    b.Navigation("InstitutionPositions");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.EarlyGovernanceScreeningEvaluationEntity", b =>
                {
                    b.Navigation("Referral");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", b =>
                {
                    b.Navigation("RiskIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
