// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence;

#nullable disable

namespace StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GovernanceIntelligenceDbContext))]
    partial class GovernanceIntelligenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("governance_intelligence")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceConditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplianceEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RequiredByDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceEvaluationId");

                    b.ToTable("compliance_conditions", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_compliance_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_comp_eval_timestamp");

                    b.ToTable("compliance_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceViolationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplianceEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceEvaluationId");

                    b.ToTable("compliance_violations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConditionalVerificationEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionalVerificationEvaluationId");

                    b.ToTable("condition_results", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpiredConditionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MandatoryConditionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingConditionsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PendingConditionsCount")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SatisfiedMandatoryCount")
                        .HasColumnType("integer");

                    b.Property<int>("SatisfiedOptionalCount")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SummaryExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalConditionsCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnsatisfiedMandatoryCount")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_cond_verif_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_cond_verif_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_cond_verif_subject_id");

                    b.ToTable("conditional_verification_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("DetectedConflictsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HighestSeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalEvaluatedDecisions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_conflict_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_conf_eval_timestamp");

                    b.ToTable("conflict_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictFindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConflictEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DetectionTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvolvedDecisionIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvolvedInstitutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConflictEvaluationId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_conf_finding_subject_id");

                    b.ToTable("conflict_findings", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AbstentionCount")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<int>("BlockingInstitutionCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConditionalApprovalCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConsensusEvaluationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ConsensusThresholdSatisfied")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MandatoryInstitutionsSatisfied")
                        .HasColumnType("boolean");

                    b.Property<int>("MissingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ParticipatingCount")
                        .HasColumnType("integer");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer");

                    b.Property<bool>("QuorumSatisfied")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SubmittedCount")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalExpectedInstitutions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_consensus_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_cons_eval_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_cons_eval_subject_id");

                    b.ToTable("consensus_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EngineType")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionName")
                        .HasDatabaseName("idx_gov_audit_action_name");

                    b.HasIndex("EngineType")
                        .HasDatabaseName("idx_gov_audit_engine_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_gov_audit_timestamp");

                    b.ToTable("governance_audit_records", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExplanationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OverallSeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_gov_expl_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_gov_expl_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_gov_expl_subject_id");

                    b.ToTable("governance_explanations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GovernanceExplanationEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlainLanguageExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresHumanAttention")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceEngine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GovernanceExplanationEvaluationId");

                    b.ToTable("governance_explanation_items", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.InstitutionPositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConsensusEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SubmittedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsensusEvaluationId");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("idx_inst_pos_institution_id");

                    b.ToTable("institution_positions", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EvaluationTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OverallRiskScore")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRecordId")
                        .IsUnique()
                        .HasDatabaseName("idx_uniq_risk_eval_audit_id");

                    b.HasIndex("EvaluationTimestamp")
                        .HasDatabaseName("idx_risk_eval_timestamp");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_risk_eval_subject_id");

                    b.ToTable("risk_evaluations", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskIndicatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndicatorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InvolvedActorsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RiskEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreContribution")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TriggeredRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RiskEvaluationId");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("idx_risk_ind_subject_id");

                    b.ToTable("risk_indicators", "governance_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceConditionEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", "ComplianceEvaluation")
                        .WithMany("Conditions")
                        .HasForeignKey("ComplianceEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceViolationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", "ComplianceEvaluation")
                        .WithMany("Violations")
                        .HasForeignKey("ComplianceEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionResultEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", "ConditionalVerificationEvaluation")
                        .WithMany("ConditionResults")
                        .HasForeignKey("ConditionalVerificationEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConditionalVerificationEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictFindingEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", "ConflictEvaluation")
                        .WithMany("Findings")
                        .HasForeignKey("ConflictEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConflictEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationItemEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", "ExplanationEvaluation")
                        .WithMany("Items")
                        .HasForeignKey("GovernanceExplanationEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExplanationEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.InstitutionPositionEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", "ConsensusEvaluation")
                        .WithMany("InstitutionPositions")
                        .HasForeignKey("ConsensusEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsensusEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceAuditRecordEntity", "AuditRecord")
                        .WithMany()
                        .HasForeignKey("AuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRecord");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskIndicatorEntity", b =>
                {
                    b.HasOne("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", "RiskEvaluation")
                        .WithMany("RiskIndicators")
                        .HasForeignKey("RiskEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiskEvaluation");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ComplianceEvaluationEntity", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConditionalVerificationEvaluationEntity", b =>
                {
                    b.Navigation("ConditionResults");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConflictEvaluationEntity", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.ConsensusEvaluationEntity", b =>
                {
                    b.Navigation("InstitutionPositions");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.GovernanceExplanationEvaluationEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StateLandGovernance.GovernanceIntelligence.Infrastructure.Persistence.Entities.RiskEvaluationEntity", b =>
                {
                    b.Navigation("RiskIndicators");
                });
#pragma warning restore 612, 618
        }
    }
}
