// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StateLandGovernance.LandIntelligence.Infrastructure.Persistence;

#nullable disable

namespace StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LandIntelligenceDbContext))]
    [Migration("20260826082050_AddGisDerivedParcelIntelligence")]
    partial class AddGisDerivedParcelIntelligence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("land_intelligence")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.EnvironmentalRestrictionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataProvenanceJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LandParcelId");

                    b.ToTable("environmental_restrictions", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.InfrastructureFeatureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("DistanceProvenanceJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SpatialReferenceSystemId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LandParcelId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.ToTable("infrastructure_features", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("land_categories", "land_intelligence");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000001"),
                            Description = "[SYNTHETIC] State-owned land category for development/testing.",
                            Name = "State Land",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000002"),
                            Description = "[SYNTHETIC] Crown land category for development/testing.",
                            Name = "Crown Land",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000003"),
                            Description = "[SYNTHETIC] Reserved land category for development/testing.",
                            Name = "Reserved Land",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000099"),
                            Description = "[SYNTHETIC] Other land category for development/testing.",
                            Name = "Other",
                            Type = 99
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AreaUnit")
                        .HasColumnType("integer");

                    b.Property<decimal>("AreaValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<MultiPolygon>("Boundary")
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("CharacteristicsProvenanceJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CurrentLandUseId")
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DivisionalSecretariat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("ElevationMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GramaNiladhariDivision")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("LandCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpatialReferenceSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("SurveyPlanReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TerrainDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("CadastralNumber")
                        .IsUnique();

                    b.HasIndex("Centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "GIST");

                    b.HasIndex("CurrentLandUseId");

                    b.HasIndex("LandCategoryId");

                    b.ToTable("land_parcels", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelGisEnrichmentSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdministrativeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("DetectedDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetectedProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("DistrictMatches")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("EnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GeometryBasis")
                        .HasColumnType("integer");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("integer");

                    b.Property<bool?>("ProvinceMatches")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LandParcelId")
                        .IsUnique();

                    b.ToTable("land_parcel_gis_enrichment_snapshots", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandRecommendationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RecommendedUseDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RecommendedUseType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SuitabilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("LandParcelId");

                    b.ToTable("land_recommendations", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandUseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("land_uses", "land_intelligence");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000001"),
                            Description = "[SYNTHETIC]",
                            Name = "Agricultural",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000002"),
                            Description = "[SYNTHETIC]",
                            Name = "Commercial",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000003"),
                            Description = "[SYNTHETIC]",
                            Name = "Industrial",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000004"),
                            Description = "[SYNTHETIC]",
                            Name = "Residential",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000005"),
                            Description = "[SYNTHETIC]",
                            Name = "Tourism",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000006"),
                            Description = "[SYNTHETIC]",
                            Name = "Conservation",
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000007"),
                            Description = "[SYNTHETIC]",
                            Name = "Mixed Use",
                            Type = 7
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000099"),
                            Description = "[SYNTHETIC]",
                            Name = "Other",
                            Type = 99
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.ParcelDerivedSoilGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DerivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GeometryBasis")
                        .HasColumnType("integer");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OverlapAreaSquareMeters")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("OverlapPercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SoilGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SoilGroupReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LandParcelId")
                        .IsUnique();

                    b.ToTable("parcel_derived_soil_groups", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.RegulatoryReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataProvenanceJson")
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("GazetteNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LandParcelId");

                    b.ToTable("regulatory_references", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.SpatialConstraintEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MultiPolygon>("ConstraintGeometry")
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("SpatialReferenceSystemId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstraintGeometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ConstraintGeometry"), "GIST");

                    b.HasIndex("LandParcelId");

                    b.ToTable("spatial_constraints", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.GisReferenceData.Entities.GisAdministrativeBoundaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<int>("BoundaryType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("BoundaryType");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFeatureId")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NOT NULL");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("IX_gis_administrative_boundaries_SourceName_SourceLayer_Sourc~1")
                        .HasFilter("\"SourceFeatureId\" IS NULL AND \"SourceFingerprint\" IS NOT NULL");

                    b.ToTable("gis_administrative_boundaries", "land_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_gis_administrative_boundaries_source_identity", "\"SourceFeatureId\" IS NOT NULL OR \"SourceFingerprint\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.GisReferenceData.Entities.GisRoadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MultiLineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (MultiLineString, 4326)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoadType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("RoadType");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFeatureId")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NOT NULL");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFingerprint")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NULL AND \"SourceFingerprint\" IS NOT NULL");

                    b.ToTable("gis_roads", "land_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_gis_roads_source_identity", "\"SourceFeatureId\" IS NOT NULL OR \"SourceFingerprint\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.GisReferenceData.Entities.GisSoilConservationAreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFeatureId")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NOT NULL");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFingerprint")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NULL AND \"SourceFingerprint\" IS NOT NULL");

                    b.ToTable("gis_soil_conservation_areas", "land_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_gis_soil_conservation_areas_source_identity", "\"SourceFeatureId\" IS NOT NULL OR \"SourceFingerprint\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.GisReferenceData.Entities.GisSoilErosionObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("ErosionRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("ObservationClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFeatureId")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NOT NULL");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("IX_gis_soil_erosion_observations_SourceName_SourceLayer_Sourc~1")
                        .HasFilter("\"SourceFeatureId\" IS NULL AND \"SourceFingerprint\" IS NOT NULL");

                    b.ToTable("gis_soil_erosion_observations", "land_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_gis_soil_erosion_observations_source_identity", "\"SourceFeatureId\" IS NOT NULL OR \"SourceFingerprint\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.GisReferenceData.Entities.GisSoilGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFeatureId")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NOT NULL");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFingerprint")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NULL AND \"SourceFingerprint\" IS NOT NULL");

                    b.ToTable("gis_soil_groups", "land_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_gis_soil_groups_source_identity", "\"SourceFeatureId\" IS NOT NULL OR \"SourceFingerprint\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.GisReferenceData.Entities.GisWaterFeatureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FeatureType")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (Geometry, 4326)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceLayer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureType");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFeatureId")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NOT NULL");

                    b.HasIndex("SourceName", "SourceLayer", "SourceFingerprint")
                        .IsUnique()
                        .HasFilter("\"SourceFeatureId\" IS NULL AND \"SourceFingerprint\" IS NOT NULL");

                    b.ToTable("gis_water_features", "land_intelligence", t =>
                        {
                            t.HasCheckConstraint("CK_gis_water_features_source_identity", "\"SourceFeatureId\" IS NOT NULL OR \"SourceFingerprint\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.EnvironmentalRestrictionEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany("EnvironmentalRestrictions")
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.InfrastructureFeatureEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany("InfrastructureFeatures")
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandUseEntity", "CurrentLandUse")
                        .WithMany("LandParcels")
                        .HasForeignKey("CurrentLandUseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandCategoryEntity", "LandCategory")
                        .WithMany("LandParcels")
                        .HasForeignKey("LandCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentLandUse");

                    b.Navigation("LandCategory");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelGisEnrichmentSnapshotEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany()
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.ParcelDerivedSoilGroupEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany()
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.RegulatoryReferenceEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany("RegulatoryReferences")
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.SpatialConstraintEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany("SpatialConstraints")
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandCategoryEntity", b =>
                {
                    b.Navigation("LandParcels");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", b =>
                {
                    b.Navigation("EnvironmentalRestrictions");

                    b.Navigation("InfrastructureFeatures");

                    b.Navigation("RegulatoryReferences");

                    b.Navigation("SpatialConstraints");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandUseEntity", b =>
                {
                    b.Navigation("LandParcels");
                });
#pragma warning restore 612, 618
        }
    }
}
