// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StateLandGovernance.LandIntelligence.Infrastructure.Persistence;

#nullable disable

namespace StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LandIntelligenceDbContext))]
    partial class LandIntelligenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("land_intelligence")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.InfrastructureFeatureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SpatialReferenceSystemId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LandParcelId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.ToTable("infrastructure_features", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("land_categories", "land_intelligence");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000001"),
                            Description = "[SYNTHETIC] State-owned land category for development/testing.",
                            Name = "State Land",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000002"),
                            Description = "[SYNTHETIC] Crown land category for development/testing.",
                            Name = "Crown Land",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000003"),
                            Description = "[SYNTHETIC] Reserved land category for development/testing.",
                            Name = "Reserved Land",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-4000-8000-000000000099"),
                            Description = "[SYNTHETIC] Other land category for development/testing.",
                            Name = "Other",
                            Type = 99
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AreaUnit")
                        .HasColumnType("integer");

                    b.Property<decimal>("AreaValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<MultiPolygon>("Boundary")
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<Guid?>("CurrentLandUseId")
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DivisionalSecretariat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("ElevationMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GramaNiladhariDivision")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("LandCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpatialReferenceSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("SurveyPlanReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TerrainDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("CadastralNumber")
                        .IsUnique();

                    b.HasIndex("Centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "GIST");

                    b.HasIndex("CurrentLandUseId");

                    b.HasIndex("LandCategoryId");

                    b.ToTable("land_parcels", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandUseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("land_uses", "land_intelligence");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000001"),
                            Description = "[SYNTHETIC]",
                            Name = "Agricultural",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000002"),
                            Description = "[SYNTHETIC]",
                            Name = "Commercial",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000003"),
                            Description = "[SYNTHETIC]",
                            Name = "Industrial",
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000004"),
                            Description = "[SYNTHETIC]",
                            Name = "Residential",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000005"),
                            Description = "[SYNTHETIC]",
                            Name = "Tourism",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000006"),
                            Description = "[SYNTHETIC]",
                            Name = "Conservation",
                            Type = 6
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000007"),
                            Description = "[SYNTHETIC]",
                            Name = "Mixed Use",
                            Type = 7
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-4000-8000-000000000099"),
                            Description = "[SYNTHETIC]",
                            Name = "Other",
                            Type = 99
                        });
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.SpatialConstraintEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MultiPolygon>("ConstraintGeometry")
                        .HasColumnType("geometry (MultiPolygon, 4326)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LandParcelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("SpatialReferenceSystemId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstraintGeometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ConstraintGeometry"), "GIST");

                    b.HasIndex("LandParcelId");

                    b.ToTable("spatial_constraints", "land_intelligence");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.InfrastructureFeatureEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany("InfrastructureFeatures")
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandUseEntity", "CurrentLandUse")
                        .WithMany("LandParcels")
                        .HasForeignKey("CurrentLandUseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandCategoryEntity", "LandCategory")
                        .WithMany("LandParcels")
                        .HasForeignKey("LandCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentLandUse");

                    b.Navigation("LandCategory");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.SpatialConstraintEntity", b =>
                {
                    b.HasOne("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", "LandParcel")
                        .WithMany("SpatialConstraints")
                        .HasForeignKey("LandParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandParcel");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandCategoryEntity", b =>
                {
                    b.Navigation("LandParcels");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandParcelEntity", b =>
                {
                    b.Navigation("InfrastructureFeatures");

                    b.Navigation("SpatialConstraints");
                });

            modelBuilder.Entity("StateLandGovernance.LandIntelligence.Infrastructure.Persistence.Entities.LandUseEntity", b =>
                {
                    b.Navigation("LandParcels");
                });
#pragma warning restore 612, 618
        }
    }
}
