"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { createContext, useContext, useState, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, CircleHelp, Download, FileText, FolderOpen, Info, ShieldCheck, Sparkles, AlertTriangle, X } from "lucide-react";
import { AppHeader } from "@/shared/components/AppHeader";
import { navigation, pathFor, screenCopy, type Screen } from "../types/flow";
import s from "./FinancialFlow.module.css";
import { LeaseCapacityPanel } from "./LeaseCapacityPanel";

const documentKinds = ["Bank statements", "Salary / income evidence", "CRIB report"] as const;
const initialFields = { income: "185000", balance: "480000", debt: "25000", lease: "35000", consistency: "0.88", grade: "B1" };
type Fields = typeof initialFields;
type FlowState = {
  fields: Fields; setFields: (fields: Fields) => void;
  files: Record<string, string>; setFiles: (files: Record<string, string>) => void;
  confirmed: boolean; setConfirmed: (value: boolean) => void;
  purpose: string; setPurpose: (value: string) => void;
  draft: string; setDraft: (value: string) => void;
  saved: string; setSaved: (value: string) => void;
};
const Context = createContext<FlowState | null>(null);
const money = (value: string | number) => `LKR ${Number(value).toLocaleString("en-LK", { maximumFractionDigits: 0 })}`;
const factors = [
  ["Debt service ratio", 25, 35, "Monthly debt and lease payment compared with income"],
  ["Income consistency", 22, 25, "Consistency of income across the evidence window"],
  ["Liquidity buffer", 20, 20, "Available balance compared with lease payments"],
  ["Credit history", 15, 20, "Bureau band B mapped to the research credit band"],
] as const;
const cases = [
  { id: "DEMO-021", purpose: "Small-scale cultivation", outcome: "Approved", grade: "B", description: "Clear purpose, an itemized operating budget and documented recurring income.", similarity: "Strong match" },
  { id: "DEMO-034", purpose: "Agricultural development", outcome: "Further review", grade: "C", description: "Income evidence needed clarification and the repayment plan was incomplete.", similarity: "Related case" },
  { id: "DEMO-048", purpose: "Community nursery", outcome: "Approved", grade: "B", description: "A phased implementation plan connected the proposed use to available resources.", similarity: "Related case" },
];
function useFlow() { const state = useContext(Context); if (!state) throw new Error("Financial flow provider is missing"); return state; }

export function FinancialFlowLayout({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  const [fields, setFields] = useState<Fields>(initialFields);
  const [files, setFiles] = useState<Record<string, string>>({});
  const [confirmed, setConfirmed] = useState(false);
  const [purpose, setPurpose] = useState("Small-scale cultivation");
  const [draft, setDraft] = useState("");
  const [saved, setSaved] = useState("");
  const current = pathname.split("/")[2] || "overview";
  const active = current === "ocr" || current === "document-issues" ? "documents" : current === "escalation" ? "assessment" : current === "proposal-editor" ? "proposal-generator" : current;
  return <Context.Provider value={{ fields, setFields, files, setFiles, confirmed, setConfirmed, purpose, setPurpose, draft, setDraft, saved, setSaved }}>
    <div className={s.shell}>
      <AppHeader />
      <div className={s.workspace}>
        <aside className={s.sidebar}>
          <Link href="/" className={s.back}><ArrowLeft size={14} /> All modules</Link>
          <p className={s.navTitle}>FINANCIAL INTELLIGENCE</p>
          <nav aria-label="Component 2 navigation">{navigation.map(item => <Link key={item.screen} href={pathFor(item.screen)} className={`${s.navLink} ${active === item.screen ? s.active : ""}`} aria-current={active === item.screen ? "page" : undefined}><span className={s.dot} />{item.label}</Link>)}</nav>
          <div className={s.sidebarNote}><ShieldCheck size={20} /><strong>Your evidence, your review</strong><p>Confirm financial information before using an assessment or proposal.</p></div>
        </aside>
        <main className={s.main}>
          <div className={s.preview}><Info size={16} /><span><strong>Design preview</strong> · Fictional sample data. Files stay in this browser session; OCR, prediction and AI generation are not connected.</span></div>
          {children}
        </main>
      </div>
    </div>
  </Context.Provider>;
}
function Go({ to, children, secondary = false }: { to: Screen; children: ReactNode; secondary?: boolean }) { return <Link className={`${s.button} ${secondary ? s.secondary : ""}`} href={pathFor(to)}>{children}<ArrowRight size={15} /></Link>; }
function Card({ title, children, className = "" }: { title?: string; children: ReactNode; className?: string }) { return <section className={`${s.card} ${className}`}>{title && <h2>{title}</h2>}{children}</section>; }
function Tag({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "good" | "warning" }) { return <span className={`${s.tag} ${tone === "good" ? s.good : tone === "warning" ? s.warning : ""}`}>{children}</span>; }
function Metric({ label, value, hint }: { label: string; value: string; hint?: string }) { return <div className={s.metric}><p>{label}</p><strong>{value}</strong>{hint && <small>{hint}</small>}</div>; }
function Notice({ children, danger = false }: { children: ReactNode; danger?: boolean }) { return <div className={`${s.notice} ${danger ? s.danger : ""}`}><AlertTriangle size={19} /><div>{children}</div></div>; }
function SampleFactors() { return <div className={s.factors}>{factors.map(([label, points, max, hint]) => <div className={s.factor} key={label}><div><strong>{label}</strong><small>{hint}</small></div><div><div className={s.bar}><span style={{ width: `${points / max * 100}%` }} /></div><small>{points} / {max}</small></div></div>)}</div>; }

export function FinancialScreen({ screen }: { screen: Screen }) {
  const flow = useFlow();
  const [notice, setNotice] = useState("");
  const [search, setSearch] = useState("");
  const [outcome, setOutcome] = useState("All outcomes");
  const [selectedCase, setSelectedCase] = useState<string | null>(null);
  const [reviewed, setReviewed] = useState(false);
  const [stage, setStage] = useState(0);
  const [generation, setGeneration] = useState(false);
  const [error, setError] = useState("");
  const [title, subtitle] = screenCopy[screen];
  const setField = (key: keyof Fields, value: string) => { flow.setFields({ ...flow.fields, [key]: value }); flow.setConfirmed(false); };
  const generate = () => {
    if (!flow.purpose.trim()) { setError("Enter the proposed lease purpose."); return; }
    flow.setDraft(`LEASE PROPOSAL — DRAFT FOR REVIEW\n\nPurpose\n${flow.purpose.trim()}\n\nProject overview\nDescribe the proposed activity, land requirements and intended community benefits.\n\nFinancial plan\nProvide verified income evidence, an itemized implementation budget, operating costs and a supported lease-payment plan.\n\nImplementation\nOutline phased activities, milestones and responsible parties.\n\nSupporting evidence\nAttach verified financial records and applicable approvals.\n\nReview note\nThis is a local sample template. No AI model or historical-case retrieval was used. Complete and independently verify all statements before submission.`);
    flow.setSaved(""); setGeneration(true); setError("");
  };
  const exportDraft = () => {
    const content = flow.saved || flow.draft;
    if (!content.trim()) { setNotice("Create a draft in Proposal Generator first."); return; }
    const url = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = "lease-proposal-draft.txt"; anchor.click(); URL.revokeObjectURL(url);
    setNotice("Draft exported for independent review.");
  };
  return <>
    <header className={s.heading}><div><p className={s.eyebrow}>COMPONENT 02 / {screen === "overview" ? "WORKSPACE" : "FINANCIAL INTELLIGENCE"}</p><h1>{title}</h1><p>{subtitle}</p></div><Tag>Sample application · C2-001</Tag></header>
    {notice && <div className={s.toast} role="status">{notice}<button aria-label="Dismiss message" onClick={() => setNotice("")}><X size={16} /></button></div>}
    {screen === "overview" && <>
      <div className={s.metrics}><Metric label="Assessment status" value="Ready to review" hint="Sample financial profile" /><Metric label="Financial eligibility" value="B · 82 / 100" hint="Deterministic sample assessment" /><Metric label="Supporting evidence" value="3 document types" hint="CRIB evidence is optional" /><Metric label="Proposal status" value={flow.saved ? "Draft saved" : "Not started"} hint="Independent review required" /></div>
      <div className={s.columns}><Card title="Your financial intelligence journey"><div className={s.steps}>{[["01", "Financial documents", "Upload and organize supporting evidence", "documents"], ["02", "Verify financial profile", "Review extraction and confirm important fields", "extracted-data"], ["03", "Financial assessment", "Understand eligibility and contributing factors", "assessment"], ["04", "Build your proposal", "Prepare, review and improve your application", "proposal-generator"]].map(([number, label, hint, to]) => <Link className={s.step} key={number} href={pathFor(to as Screen)}><span className={s.stepNumber}>{number}</span><div><strong>{label}</strong><small>{hint}</small></div><ChevronRight size={18} /></Link>)}</div></Card><Card title="Application at a glance"><dl className={s.details}><dt>Application reference</dt><dd>C2-001 · sample</dd><dt>Proposed use</dt><dd>{flow.purpose}</dd><dt>Applicant type</dt><dd>Individual applicant</dd><dt>Evidence window</dt><dd>Six months</dd></dl><div className={s.divider} /><p className={s.muted}>Start with your documents, then review the financial profile before preparing a proposal.</p><Go to="documents">Review financial documents</Go></Card></div>
      <Card title="Decision support with a clear evidence trail"><div className={s.threeColumns}>{[[ShieldCheck, "Verified inputs", "Financial evidence stays separate from assumptions."], [CircleHelp, "Explainable results", "See the factors behind each assessment."], [Sparkles, "Reviewable proposals", "Every draft remains subject to your review."]].map(([Icon, label, text], index) => { const Component = Icon as typeof ShieldCheck; return <div className={s.feature} key={index}><Component size={22} /><strong>{label as string}</strong><p>{text as string}</p></div>; })}</div></Card>
    </>}
    {screen === "documents" && <>
      <div className={s.columns}><Card title="Upload supporting documents"><p className={s.muted}>Select PDF, PNG or JPEG files up to 10 MB each. Selecting a file here does not upload it or run OCR.</p><div className={s.uploadList}>{documentKinds.map((kind, index) => <div className={s.uploadRow} key={kind}><div className={s.fileIcon}><FileText size={23} /></div><div className={s.fileInfo}><strong>{kind}</strong><small>{flow.files[kind] || (index === 2 ? "Optional supporting credit evidence" : index === 0 ? "Statements covering the evidence period" : "Salary slips or business income evidence")}</small></div><label className={s.fileButton}>{flow.files[kind] ? "Replace file" : "Choose file"}<input aria-label={kind} type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024 || !/\.(pdf|png|jpe?g)$/i.test(file.name)) { setError("Choose a PDF, PNG or JPEG file no larger than 10 MB."); event.target.value = ""; return; } flow.setFiles({ ...flow.files, [kind]: file.name }); setError(""); }} /></label>{flow.files[kind] && <button className={s.iconButton} aria-label={`Remove ${kind}`} onClick={() => flow.setFiles(Object.fromEntries(Object.entries(flow.files).filter(([key]) => key !== kind)))}><X size={15} /></button>}</div>)}</div>{error && <p role="alert" className={s.error}>{error}</p>}<div className={s.actions}><Go to="ocr">Preview processing journey</Go><Go to="document-issues" secondary>Review document issues</Go></div></Card><Card title="Before you continue"><ul className={s.checkList}><li><Check size={16} /> Complete and readable pages</li><li><Check size={16} /> Consistent evidence periods</li><li><Check size={16} /> Appropriate income evidence</li><li><Check size={16} /> Permission to process documents</li></ul><Notice>CRIB is optional. A missing report must not be interpreted as poor credit or zero debt.</Notice></Card></div>
    </>}
    {screen === "ocr" && <Card title="Sample extraction workflow"><div className={s.progressHeader}><div><strong>{["Documents selected", "Reading text and tables", "Checking financial fields", "Ready for your review"][stage]}</strong><p className={s.muted}>Preview the steps; no selected document is sent to Azure.</p></div><Tag tone={stage === 3 ? "good" : "neutral"}>{stage + 1} / 4</Tag></div><div className={s.progress}><span style={{ width: `${(stage + 1) * 25}%` }} /></div>{["Document intake", "Azure OCR extraction", "Field validation", "Human confirmation"].map((label, index) => <div className={s.processRow} key={label}><span className={index <= stage ? s.processDone : s.processPending}>{index < stage ? <Check size={16} /> : index + 1}</span><strong>{label}</strong><Tag>{index < stage ? "Sample step complete" : index === stage ? "Current preview step" : "Next step"}</Tag></div>)}<div className={s.actions}>{stage < 3 ? <button className={s.button} onClick={() => setStage(stage + 1)}>Next preview step<ArrowRight size={15} /></button> : <Go to="extracted-data">Review sample financial data</Go>}</div></Card>}
    {(screen === "extracted-data" || screen === "assessment") && <LeaseCapacityPanel income={flow.fields.income} debt={flow.fields.debt} lease={flow.fields.lease} />}
    {screen === "extracted-data" && <><div className={s.metrics}><Metric label="Monthly income" value={money(flow.fields.income)} /><Metric label="Monthly debt" value={money(flow.fields.debt)} /><Metric label="Requested lease payment" value={money(flow.fields.lease)} /></div><div className={s.columns}><Card title="Financial profile — editable sample"><div className={s.fieldGrid}>{Object.entries({ income: "Average monthly income (LKR)", balance: "Average account balance (LKR)", debt: "Verified monthly debt (LKR)", lease: "Requested monthly lease payment (LKR)", consistency: "Income consistency ratio (0–1)" }).map(([key, label]) => <label className={s.field} key={key}>{label}<input type="number" min="0" max={key === "consistency" ? "1" : undefined} step="0.01" value={flow.fields[key as keyof Fields]} onChange={e => setField(key as keyof Fields, e.target.value)} /></label>)}<label className={s.field}>Original CRIB risk grade<select value={flow.fields.grade} onChange={e => setField("grade", e.target.value)}>{["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3", "D1", "D2", "D3", "E1", "E2", "E3", "XX", "Not supplied"].map(grade => <option key={grade}>{grade}</option>)}</select></label></div><label className={s.checkbox}><input type="checkbox" checked={flow.confirmed} onChange={e => flow.setConfirmed(e.target.checked)} /> I have reviewed these sample fields.</label><p className={s.muted}>The capacity calculation updates with these fields. The sample score remains fixed until the scoring API is connected.</p><Go to="assessment">View sample assessment</Go></Card><Card title="Items needing confirmation"><Notice>Outstanding debt is not a monthly payment. Confirm active facilities and repayment schedules.</Notice><dl className={s.details}><dt>CRIB grade</dt><dd>Keep the original subgrade</dd><dt>XX / missing evidence</dt><dd>Requires review</dd><dt>Default history</dt><dd>Verify repayment evidence</dd><dt>Disputed records</dt><dd>Review before assessment</dd></dl><Go to="document-issues" secondary>Review evidence issues</Go></Card></div></>}
    {screen === "document-issues" && <><Notice><strong>Sample evidence issues require your attention</strong><p>Unreadable or uncertain fields need correction before a real assessment can proceed.</p></Notice><div className={s.columns}><Card title="Required corrections">{[["Bank statement — incomplete page", "Upload all pages for the evidence period.", "Required"], ["Income evidence — unclear amount", "Confirm recurring income against the original record.", "Required"], ["CRIB repayment evidence", "Verify monthly obligations; do not infer them from the outstanding balance.", "Review"]].map(([label, hint, status]) => <div key={label} className={s.issue}><div><strong>{label}</strong><small>{hint}</small></div><Tag tone="warning">{status}</Tag></div>)}</Card><Card title="Correct and review"><p className={s.muted}>Replace the relevant file or clarify its extracted fields. Real reprocessing will become available with the document API.</p><Go to="documents">Choose replacement files</Go><div className={s.divider} /><Go to="extracted-data" secondary>Review sample fields</Go></Card></div></>}
    {(screen === "assessment" || screen === "escalation") && <>
      {screen === "escalation" && <Notice danger><strong>Higher-risk sample: human review required</strong><p>This is a separate fictional scenario, not a decision about the edited profile.</p></Notice>}
      <div className={s.resultColumns}><section className={s.scoreCard}><p>FINANCIAL ELIGIBILITY</p><strong className={s.bigGrade}>{screen === "escalation" ? "D" : "B"}</strong><h2>{screen === "escalation" ? "Escalate for review" : "Strong financial eligibility"}</h2><span>{screen === "escalation" ? "38" : "82"} / 100 · fixed sample result</span><div className={s.scoreDivider} /><p>Research scoring contract v1</p><small>Advisory assessment · final review required</small></section><Card title={screen === "escalation" ? "Risk indicators" : "Assessment summary"}>{screen === "assessment" ? <SampleFactors /> : <><div className={s.issue}><strong>Debt-service pressure</strong><Tag tone="warning">Review</Tag></div><div className={s.issue}><strong>Unverified recurring income</strong><Tag tone="warning">Evidence needed</Tag></div><div className={s.issue}><strong>Repayment history concerns</strong><Tag tone="warning">Clarification</Tag></div></>}<p className={s.muted}>CRIB grades, financial eligibility and lease approval probability are separate outputs.</p></Card></div><div className={s.columns}><Card title="What this means"><p className={s.muted}>{screen === "escalation" ? "Resolve the evidence gaps and ask an authorized reviewer to assess repayment capacity before proceeding." : "The sample falls within research band B. A real result needs verified inputs and the connected scoring service."}</p><Go to={screen === "escalation" ? "document-issues" : "prediction"}>{screen === "escalation" ? "Review supporting evidence" : "Explore prediction preview"}</Go></Card><Card title="Assessment alternatives"><Go to={screen === "escalation" ? "assessment" : "escalation"} secondary>{screen === "escalation" ? "Return to standard sample" : "View higher-risk scenario"}</Go><p className={s.muted}>Explore both states without changing applicant evidence.</p></Card></div>
    </>}
    {screen === "prediction" && <><div className={s.resultColumns}><section className={s.scoreCard}><p>ESTIMATED APPROVAL · ILLUSTRATION</p><strong className={s.bigPercent}>76%</strong><h2>Sample prediction display</h2><span>No model has been run</span><div className={s.scoreDivider} /><small>Illustrative UI values, not calibrated probabilities</small></section><Card title="Prediction interpretation">{[["Approval likely", 76], ["Further review", 18], ["Rejection risk", 6]].map(([label, percent], index) => <div className={s.probability} key={label}><strong>{label}</strong><div className={s.bar}><span className={index === 1 ? s.amberBar : index === 2 ? s.redBar : ""} style={{ width: `${percent}%` }} /></div><span>{percent}%</span></div>)}<Notice>These values are design examples. Historical outcomes and model validation are required before real predictions.</Notice></Card></div><div className={s.columns}><Card title="Example prediction factors"><dl className={s.details}><dt>Recurring income</dt><dd>Supporting evidence</dd><dt>Debt service capacity</dt><dd>Review monthly obligations</dd><dt>Financial eligibility</dt><dd>Separate scoring output</dd><dt>Missing credit evidence</dt><dd>Uncertainty, not rejection</dd></dl></Card><Card title="Continue with the evidence"><Go to="historical-cases">View similar sample cases</Go><div className={s.divider} /><Go to="proposal-generator" secondary>Continue to proposal</Go></Card></div></>}
    {screen === "historical-cases" && <Card title="Comparable cases — fictional examples"><div className={s.filters}><label className={s.field}>Search sample cases<input placeholder="Search by purpose or reference" value={search} onChange={e => setSearch(e.target.value)} /></label><label className={s.field}>Decision outcome<select value={outcome} onChange={e => setOutcome(e.target.value)}>{["All outcomes", "Approved", "Further review"].map(value => <option key={value}>{value}</option>)}</select></label></div><div className={s.tableWrap}><table><thead><tr><th>Case reference</th><th>Proposed use</th><th>Financial grade</th><th>Outcome</th><th>Similarity</th><th><span className={s.srOnly}>Details</span></th></tr></thead><tbody>{cases.filter(item => `${item.id} ${item.purpose}`.toLowerCase().includes(search.toLowerCase()) && (outcome === "All outcomes" || item.outcome === outcome)).map(item => <tr key={item.id}><td>{item.id}</td><td>{item.purpose}</td><td>{item.grade}</td><td><Tag tone={item.outcome === "Approved" ? "good" : "warning"}>{item.outcome}</Tag></td><td>{item.similarity}</td><td><button className={s.textButton} onClick={() => setSelectedCase(item.id)}>View case</button></td></tr>)}</tbody></table></div>{!cases.some(item => `${item.id} ${item.purpose}`.toLowerCase().includes(search.toLowerCase()) && (outcome === "All outcomes" || item.outcome === outcome)) && <p className={s.empty}>No sample cases match your search.</p>}{selectedCase && <div className={s.caseDetail}><button className={s.iconButton} aria-label="Close case details" onClick={() => setSelectedCase(null)}><X size={16} /></button><h3>{selectedCase} · Sample case insight</h3><p>{cases.find(item => item.id === selectedCase)?.description}</p><small>Fictional example. No retrieval engine was used.</small></div>}<div className={s.actions}><Go to="proposal-generator">Use insights to prepare a draft</Go></div></Card>}
    {screen === "proposal-generator" && <div className={s.columns}><Card title="Proposal information"><label className={s.field}>Proposed lease purpose<textarea rows={3} value={flow.purpose} onChange={e => { flow.setPurpose(e.target.value); setGeneration(false); }} placeholder="Describe the intended use of the land" /></label><div className={s.divider} /><dl className={s.details}><dt>Financial profile</dt><dd>{flow.confirmed ? "Sample fields reviewed" : "Awaiting sample review"}</dd><dt>Historical evidence</dt><dd>Fictional examples only</dd><dt>Draft method</dt><dd>Local editable template</dd></dl>{error && <p role="alert" className={s.error}>{error}</p>}<button className={s.button} onClick={generate}><Sparkles size={16} />Create sample draft</button>{generation && <div className={s.success} role="status"><CheckCircle2 size={18} /><span>Sample template prepared.</span><Go to="proposal-editor">Review draft</Go></div>}</Card><Card title="What a strong proposal includes"><ul className={s.checkList}><li><Check size={16} /> A clear and supported lease purpose</li><li><Check size={16} /> Verified financial capacity</li><li><Check size={16} /> An itemized implementation budget</li><li><Check size={16} /> Practical milestones and timelines</li><li><Check size={16} /> Required approvals and attachments</li></ul><p className={s.muted}>Future AI suggestions will need references to retrieved evidence. They must never invent financial facts.</p></Card></div>}
    {screen === "proposal-editor" && <div className={s.columns}><Card title="Your proposal draft">{flow.draft ? <><label className={s.field}>Draft content<textarea className={s.editor} value={flow.draft} onChange={e => { flow.setDraft(e.target.value); flow.setSaved(""); }} rows={17} /></label><div className={s.actions}><button className={s.button} onClick={() => { if (!flow.draft.trim()) { setNotice("Enter draft content before saving."); return; } flow.setSaved(flow.draft); setNotice("Draft saved for this session. Reloading clears it."); }}>Save draft</button><Go to="proposal-ready" secondary>Review readiness</Go></div></> : <div className={s.empty}><FolderOpen size={30} /><p>No proposal draft yet.</p><Go to="proposal-generator">Create a sample draft</Go></div>}</Card><Card title="Recommendations to consider">{[["Clarify the operating budget", "List startup and recurring costs with evidence."], ["Add a phased timeline", "Connect milestones to available resources."], ["Verify financial statements", "Use confirmed facts and distinguish estimates."]].map(([label, hint]) => <div className={s.recommendation} key={label}><Sparkles size={16} /><div><strong>{label}</strong><p>{hint}</p></div></div>)}<Tag>Static review prompts</Tag><div className={s.divider} /><Go to="explainable-ai" secondary>Understand the evidence</Go></Card></div>}
    {screen === "explainable-ai" && <><Card title="Evidence behind the proposal"><div className={s.tableWrap}><table><thead><tr><th>Recommendation</th><th>Evidence needed</th><th>Current status</th></tr></thead><tbody>{[["Support repayment capacity", "Verified income, debt and lease-payment inputs"], ["Explain credit evidence", "CRIB subgrade, facilities and repayment history"], ["Strengthen project structure", "Relevant cases and applicable proposal requirements"], ["Document operating feasibility", "Applicant budget, milestones and supporting records"]].map(([label, evidence]) => <tr key={label}><td>{label}</td><td>{evidence}</td><td><Tag tone="warning">Not linked in preview</Tag></td></tr>)}</tbody></table></div></Card><div className={s.columns}><Card title="How evidence will be used"><p className={s.muted}>Verified financial facts feed the assessment. Retrieved case passages support proposal suggestions. Every suggestion should show its source and remain editable.</p><Go to="historical-cases">Explore sample case insights</Go></Card><Card title="What requires your review"><Notice>CRIB default probability is not lease approval probability. Neither output replaces an authorized decision.</Notice><Go to="proposal-editor" secondary>Return to proposal editor</Go></Card></div></>}
    {screen === "proposal-ready" && <><div className={s.readiness}><CheckCircle2 size={28} /><div><h2>{flow.saved ? "Your draft is saved for review" : "Complete your proposal draft"}</h2><p>{flow.saved ? "Review the checklist before exporting. Submission is not connected." : "Create and save a proposal in the editor before exporting."}</p></div><Tag tone={flow.saved ? "good" : "warning"}>{flow.saved ? "Draft available" : "Draft pending"}</Tag></div><div className={s.columns}><Card title="Final review checklist"><ul className={s.checkList}>{["Applicant statements are accurate", "Financial evidence has been independently verified", "Estimates and assumptions are clearly identified", "Required documents and approvals are attached", "All proposal sections have been reviewed"].map(label => <li key={label}><CheckCircle2 size={17} />{label}</li>)}</ul><label className={s.checkbox}><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /> I have reviewed the sample draft checklist.</label></Card><Card title="Draft actions"><dl className={s.details}><dt>Version</dt><dd>Session draft</dd><dt>Saved content</dt><dd>{flow.saved ? "Available" : "Not saved"}</dd><dt>Submission status</dt><dd>Not submitted</dd></dl><div className={s.actions}><button className={s.button} onClick={exportDraft} disabled={!flow.saved || !reviewed}><Download size={16} />Export draft (.txt)</button><Go to="proposal-editor" secondary>Edit proposal</Go></div><p className={s.muted}>Drafts are kept in memory only. Export before leaving or reloading this session.</p><button className={s.disabledButton} disabled>Submission available after integration</button></Card></div></>}
    <footer className={s.footer}><ShieldCheck size={14} /> Financial intelligence supports review. Final decisions remain with authorized officers.</footer>
  </>;
}
