using StateLandGovernance.LandIntelligence.Application.DTOs;

namespace StateLandGovernance.LandIntelligence.Application.Commands;

public sealed record GenerateLandRecommendationCommand(LandRecommendationRequest Request);
