using StateLandGovernance.LandIntelligence.Application.DTOs;

namespace StateLandGovernance.LandIntelligence.Application.Queries;

public sealed record SearchLandRecommendationsQuery(LandRecommendationSearchRequest Request);
